name: "Lint (desktop)"

on:
    # Run on every push to a branch other than main that changes desktop/
    push:
        branches-ignore: [main]
        paths:
            - "desktop/**"
            - ".github/workflows/desktop-lint.yml"

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: desktop
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node and enable yarn caching
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"
                  cache-dependency-path: "desktop/yarn.lock"

            - run: yarn install

            - run: yarn lint
